### ISSUE TITLE
コードレビュー by vv

### ISSUE THREAD

**Issue by vvakame** [sakura818/write-http-server-01#13]
* `./gradlew clean run` して http://localhost:8080/ にアクセスすると `java.io.FileNotFoundException` が発生する
* http://localhost:8080/index.html にアクセスすると謎の人間には理解できなさそうなログがばーっと出てくる
  * いらないログは出さないほうがいいかも…
  * gifです のところに jpegの画像が出てくる
    * よく見ると拡張子はgifだ
    * 見てたらpngに変わった…アニメーションgifだ…
    * 紛らわしいのはよくないことだ
* HttpRequestのコンストラクタ
  * `new BufferedReader(new InputStreamReader(new BufferedInputStream(...` みたいな構造になってるけどこれは全部必要なのですか？
    * ぱっと見、2回BufferedXxx的な名前が出てきているのでどっちか無駄じゃないのみたいな気持ちになる
  * `String requestLine; requestLine = bufferedReader.readLine();` 的なコードは単に `String requestLine = bufferedReader.readLine();` と書いたほうが素直です
* HttpRequest#parseRequestUri について
  * `this.requestUri` に値をセットするのと、その値を返すのと、両方行っているのはあまりよくなさそう
    * parseRequestUri という名前から期待される動作は "引数に与えた文字列をパースしRequest URIを返す" だと思います
    * 副作用として this.requestUri に値をセットするのはメソッド名から推測するにこのメソッドの役割ではないでしょう
    * 一方、 this.uriPath に値をセットするのはparseUriPathメソッド内ではなくて呼び出し元で行っている(こっちのほうが良い
  * 確認してないけど、直感的にこのサーバは http://localhost:8080/sub-directory/index.html みたいなリクエストを処理できない気がする
* HttpResponseクラスについて
  * ブラウザに返却するべきコンテンツとして `File file` を使うのは次の課題を行うにあたり自由度が低そうに思える
  * 具体的に、メモリ上で生成した動的なコンテンツを返却できないのでは？
  * この課題をいつ解決するかはおまかせします(今の課題中に解決してもよいし、次の課題まで困らないなら次の課題の時に考えることにしてもよい
* HttpResponse#createHttpResponseContent
  * レスポンス全文の末尾に CRLF を付与する処理はいるのだろうか？(HTTPの仕様上必要か？
* HttpResponseStatusLineBuilder クラスについて
  * サーバ側がおかしい場合の 500 Internal Server Error を追加し、一部例外の対応として使えないか検討してみよう
* HttpResponseStatusLineBuilder#catchReasonPhrase について
  * 知らないコードだった場合も何かしらの文字列を返したほうがいいと思う(仕様上何を入れても問題ないはずなので null よりは Unknown とかのほうが妥当だろうという気持ち
* 全体的に例外発生時の処理が画一的すぎると思う 各例外について発生しうるシチュエーションをチェックしてみよう
  * ざっくり次の3種類の対応に分類できると思う
    * クライアントが悪いパターン(Bad Request
    * サーバ側が悪いが処理継続可能なパターン(Internal Server Error
      * どの例外がこれに当てはまるか判別するのは結構難しいかもしれない
    * サーバ側が悪い上に処理継続不可能(現状維持
* テストについて
  * HttpResponseMessageBodyBuilderTest とか
    * `new HttpResponseMessageBodyBuilder(indexHtml);` とした後に作ったインスタンス使わないのは無駄っぽい(使うか消すかしよう
      * 後のテスト内容見るとインスタンスの `.build()` を呼んで結果を見るのが目的っぽいな
  * テストを書くときは、どのクラスのどのメソッドのどういう性質へのテストなのか を明確にしたほうがよいだろう
    * 今のところ どのクラス(インスタンス)の性質へのテスト しかテスト上記述されていなさそう(テストのクラス名やメソッド名の問題
    * このへんasada君が情報持ってるはず

総評：細かい指摘が多いのでそろそろレビュー通りそうな気配を感じられるようになってきた 🙆‍♂️

**Comment by sakura818** [comment]
* [x] ./gradlew clean run して http://localhost:8080/ にアクセスすると java.io.FileNotFoundException が発生する
* [x] http://localhost:8080/index.html にアクセスすると謎の人間には理解できなさそうなログがばーっと出てくる　いらないログは出さないほうがいいかも…
* [x] gifなおす
* [x] HttpRequestのコンストラクタ　new BufferedReader(new InputStreamReader(new BufferedInputStream(... →　BufferedReaderは文字型入力ストリームのreadLineメソッドを使用するため、InputStreamReaderはバイト・ストリームから文字ストリームへの橋渡しの役目のため、BufferedInputStreamはバイト入力ストリームにいれるため
* [x] String requestLine; requestLine = bufferedReader.readLine(); 的なコードは単に String requestLine = bufferedReader.readLine(); と書いたほうが素直です
* [x] HttpRequest#parseRequestUri についてthis.requestUri に値をセットするのと、その値を返すのと、両方行っているのはあまりよくなさそう
* [x] parseRequestUri という名前 副作用として this.requestUri に値をセットするのはメソッド名から推測するにこのメソッドの役割ではない
* [x]  一方、 this.uriPath に値をセットするのはparseUriPathメソッド内ではなくて呼び出し元で行っている(こっちのほうが良い
* [x]  http://localhost:8080/sub-directory/index.html みたいなリクエストを処理できるようにする
* [ ] ブラウザに返却するべきコンテンツとして File file を使うの自由度が低そう
具体的に、メモリ上で生成した動的なコンテンツを返却できないのでは？
この課題をいつ解決するかはおまかせします(今の課題中に解決してもよいし、次の課題まで困らないなら次の課題の時に考えることにしてもよい
* [x] レスポンス全文の末尾に CRLF を付与する処理はいるのだろうか？(HTTPの仕様上必要か？
* [x] サーバ側がおかしい場合の 500 Internal Server Error を追加し、一部例外の対応として使えないか検討してみよう
* [x] 知らないコードだった場合も何かしらの文字列を返したほうがいいと思う(仕様上何を入れても問題ないはずなので null よりは Unknown とかのほうが妥当だろうという気持ち
* [x] 全体的に例外発生時の処理が画一的すぎると思う 各例外について発生しうるシチュエーションをチェックしてみよう

テストについて
* [x] HttpResponseMessageBodyBuilderTest とか
new HttpResponseMessageBodyBuilder(indexHtml); とした後に作ったインスタンス使わないのは無駄っぽい(使うか消すかしよう
* [x] テストを書くときは、どのクラスのどのメソッドのどういう性質へのテストなのか を明確にする
今のところ どのクラス(インスタンス)の性質へのテスト しかテスト上記述されていなさそう(テストのクラス名やメソッド名の問題

**Comment by sakura818** [comment]
ブラウザに返却するべきコンテンツとして File file を使うの自由度が低そう→次の課題のときに考える
