### ISSUE TITLE
ホワイトボックステストの準備

### ISSUE THREAD

**Issue by sakura818** [sakura818/write-http-server-01#19]

**Comment by sakura818** [comment]
**要求仕様に関するチェックリスト**
要求仕様

"普通のWebサーバ"を作る。

静的リソースの配信ができ、最新のChromeで閲覧することができる
Firefoxでも少し確認するとなお良い
HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること
"普通"が指す範囲を検討し、実装する
200, 404 など各種ステータスコードのサポートがあること
その他色々

- [x] 静的リソースの配信ができ、最新のChromeで閲覧することができる→バージョン 58.0.3029.110 (64-bit)(Chrome最新版であることは確認済)で閲覧することができた
- [x] Firefoxでも少し確認するとなお良い→Firefox53.0.3(64ビット)(Firefox最新版であることは確認済み)で閲覧することができた
- [x] HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること→表示できる
- [x] 200, 404 など各種ステータスコードのサポートがあること→サポートしている

**Comment by sakura818** [comment]
- [ ] 静的リソースの配信ができ、最新のChromeで閲覧することができる→バージョン 58.0.3029.110 (64-bit)(最新版であることも確認)で閲覧することができる
- [ ] Firefoxでも少し確認するとなお良い→
- [ ] HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること→表示できる
- [ ] 200, 404 など各種ステータスコードのサポートがあること→サポートしている

**Comment by sakura818** [comment]
**asadaさんのホワイトボックステストを参考にしたチェックリスト**

- [ ] /music/sample.mp3 もちゃんと配信されて落ちてきた
- [x] 存在しないファイルに対する拡張子のないリクエストでサーバーが落ちる　localhost:8080/bar にアクセスすると→not found なのでok
- [ ] 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる　hoge ファイルを追加したうえで localhost:8080/hoge にアクセスすると
- [ ] /foo/ にアクセスしたときに /foo/index.html が配信されずサーバーが落ちる　/ にアクセスしたときの /index.html の配信と一貫性がない→/foo/だとnotfoundになるので修正→
- [ ] 名前に日本語を含むファイルが配信できていない　寿司.txt を用意しても localhost:8080/寿司.txt でアクセスできない→notfoundになるので修正→
- [x] 巨大なファイルの配信中に別のクライアントからのリクエストも止まる　2.2GBのファイルを落としながら別のタブでindex.htmlを表示しようとしてもレスポンスが返ってこない。→→README.mdにリクエストを同時にさばけない旨を記述する
- [x] ファイル名の先頭に . が付いたHTMLファイルが表示できない　.ignored.html を作成するとファイルのダウンロードが始まり、HTMLが表示されない→html表示できた
- [ ] http://localhost:8080/?foo=bar がNotFoundになる　http://localhost:8080/index.html?foo=bar は表示される
- [x] Shift-JIS形式で保存したHTMLファイルが文字化けする　常にContent-Typeのencofingがutf-8なのでこうなる　文字コードの指定は仕様に書くようにする→README.mdに文字コードはUTF-8を使用してくださいと記述する
- [x] Content-Typeの確認
- [x] 画像著作権フリーか？

**Comment by sakura818** [comment]
**atozeさんのホワイトボックステストを参考にしたチェックリスト**

- [x] JavaScriptファイルのContent-Typeはapplication/javascript が推奨
- [x] JPEGファイルのContent-Typeはimage/jpeg
- [x] 複数リクエスト同時にさばける→README.mdにリクエストを同時にさばけない旨を記述する
- [ ] 巨大なファイルを配信しようとするとサーバーが落ちる　1.9GBのHTMLファイルを配信させたら途中で落ちた

**Comment by sakura818** [comment]
**上記のチェックリストの中でまだチェックがついてないものをまとめた**

- [x] /music/sample.mp3 もちゃんと配信されて落ちてきた→ダミーファイルとしてddコマンドでsample.mp3つくる。content-typeにmp3追加する(content-typeのmp3も追加)→mp3を配信出来るようになったがBrokenPipeエラーが起こってしまう。BrokenPipeエラーはプログラムのエラーではなく通信のエラーなので現段階でこれ以上なおすのは厳しそう。→一旦ここでうちやめ　
- [ ] 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる　hoge ファイルを追加したうえで( http://localhost:8080/hoge )にアクセスするとエラーが起こる→sample.cssとsample.jsがある場合、( http://localhost:8080/sample )とリクエストして404 Not Foundにするのが正しい挙動だと思う。→質問する
- [ ] /foo/ にアクセスしたときに /foo/index.html が配信されずサーバーが落ちる　/ にアクセスしたときの /index.html の配信と一貫性がない→( http://localhost:8080 ),( http://localhost:8080/ ),( http://localhost:8080/index.html )のときにindex.htmlが表示できるようにしている。( http://localhost:8080/foo/ )のときにindex.htmlを表示するのは正しいキョドではないと思う(404を表示するのが正しい挙動だと思う)。→質問する
- [x] 名前に日本語を含むファイルが配信できていない　寿司.txt を用意しても localhost:8080/寿司.txt でアクセスできない→notfoundになるので修正→ちゃんと表示できるようになった
- [ ] http://localhost:8080/?foo=bar がNotFoundになる　http://localhost:8080/index.html?foo=bar は表示される→まずrfc2616の3.2を読む→今の課題では必要ないのでは…？次の課題でPOSTメソッドが必要になるのでそのときに実装しようと思う。一応質問
- [x] 巨大なファイルを配信しようとするとサーバーが落ちる　1.9GBのHTMLファイルを配信させたら途中で落ちた→1GBのダミーファイルをddコマンドでlargeCapacity.txtをつくり、配信できているかどうか確認する。→配信できるようになった


**「( http://localhost:8080/?foo=bar )がNotFoundになる。( http://localhost:8080/index.html?foo=bar )は表示される」に関しては、URLのクエリの部分を実装していないのでまずRFC2616の3.2などを読んだところ今の課題では必要ないのではと考えた。次の課題でPOSTメソッドが必要になるのでそのときに実装しようと思う。

**Comment by sakura818** [comment]
**質問するリスト**

- [x] 「存在するファイルに対する拡張子のないリクエストでサーバーが落ちる　hoge ファイルを追加したうえで( http://localhost:8080/hoge )にアクセスするとエラーが起こる」に関して→sample.cssとsample.jsがある場合、( http://localhost:8080/sample )とリクエストして404 Not Foundにするのが正しい挙動だと思っていていまはそのように実装している。それか拡張子をもたないファイルをローカルのリソースフォルダにいれて配信できるかってことなのかな(これはなさそう)。
勘違いしている可能性がありそうなので質問する。
- [x] 「/foo/ にアクセスしたときに /foo/index.html が配信されずサーバーが落ちる　/ にアクセスしたときの /index.html の配信と一貫性がない」に関して→( http://localhost:8080 ),( http://localhost:8080/ ),( http://localhost:8080/index.html )のときにindex.htmlが表示するようにいまは実装している。( http://localhost:8080/foo/ )のときにindex.htmlを表示するのは正しい挙動ではないと思う。( http://localhost:8080/foo/ )のときは404 Not Foundを表示するのが正しい挙動だと思っていていまはそのように実装している)。
これに関しても上記と同様、認識が間違っていないかどうか確認する。

**Comment by vvakame** [comment]
1つ目 実際に sample というファイルが置いてある時に http://localhost:8080/sample にアクセスしたらそのファイルがダウンロードできたりすること。
ファイルがあるならアクセスできるのが期待する動作(拡張子の有無や未知の拡張子であっても同様)。
この場合、どう表示するのが正しいのか？ということは(拡張子から判別できないので)不明なので、 "ダウンロードできる" が一般解だと思います。

2つ目 一般的だと我々が考えているルールとして、 `/**/` にアクセスした時、 `/**/index.html` が返される 的なことです。(index.phpが返ってくる可能性もあるけど我々の課題では index.html だよなという共通認識があるはず
この場合、 `/` にアクセスしたら `/index.html` だし、 `/foo/` にアクセスしたら `/foo/index.html` が返るし  `/monosugoku/nagaku/fukai/` にアクセスしたら `/monosugoku/nagaku/fukai/index.html` が返ってきて欲しい。ということです。

**Comment by sakura818** [comment]
一通り変更が修正したので、以前成功していたテストも含めて再度全てチェックする。

- [x] 静的リソースの配信ができ、最新のChromeで閲覧することができる→バージョン 58.0.3029.110 (64-bit)(Chrome最新版であることは確認済)で閲覧することができた
- [x] Firefoxでも少し確認するとなお良い→Firefox53.0.3(64ビット)(Firefox最新版であることは確認済み)で閲覧することができた
- [x] HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること→表示できる
- [x] 200, 404 など各種ステータスコードのサポートがあること→サポートしている
- [x] /sample.mp3 もちゃんと配信されて落ちてきた
- [x] 存在しないファイルに対する拡張子のないリクエストでサーバーが落ちる　localhost:8080/bar にアクセスすると→not found なのでok
- [x] 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる　hoge ファイルを追加したうえで localhost:8080/hoge にアクセスすると
- [x] /foo/ にアクセスしたときに /foo/index.html が配信されずサーバーが落ちる　/ にアクセスしたときの /index.html の配信と一貫性がない→/foo/だとnotfoundになるので修正→
- [x] 名前に日本語を含むファイルが配信できていない　寿司.txt を用意しても localhost:8080/寿司.txt でアクセスできない→notfoundになるので修正→
- [x] 巨大なファイルの配信中に別のクライアントからのリクエストも止まる　2.2GBのファイルを落としながら別のタブでindex.htmlを表示しようとしてもレスポンスが返ってこない。→README.mdにリクエストを同時にさばけない旨を記述する
- [x] ファイル名の先頭に . が付いたHTMLファイルが表示できない　.ignored.html を作成するとファイルのダウンロードが始まり、HTMLが表示されない→html表示できた
- [x] http://localhost:8080/?foo=bar がNotFoundになる　http://localhost:8080/index.html?foo=bar は表示される→URLのクエリの部分を実装していないのでまずRFC2616の3.2などを読んだところ今の課題では必要ないのではと考えた。次の課題でPOSTメソッドが必要になるのでそのときに実装しようと思う。
- [x] Shift-JIS形式で保存したHTMLファイルが文字化けする　常にContent-Typeのencofingがutf-8なのでこうなる　文字コードの指定は仕様に書くようにする→README.mdに文字コードはUTF-8を使用してくださいと記述する
- [x] Content-Typeの確認
- [x] 画像著作権フリーか？→フリー（画像などは自分で作成したもの）
- [x] JavaScriptファイルのContent-Typeはapplication/javascript が推奨
- [x] JPEGファイルのContent-Typeはimage/jpeg
- [x] 複数リクエスト同時にさばける→README.mdにリクエストを同時にさばけない旨を記述する
- [x] 巨大なファイルを配信できるか　http://localhost:8080/largeCapacity.txt
- [x] Chromeで http://localhost:8080/index.html で表示できるか
- [x] Chromeで http://localhost:8080/hoge.html が404表示できるか
- [x] Chromeで http://localhost:8080/ でindex.html 表示できるか
- [x] Chromeで http://localhost:8080 で index.html 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/index.html でdummyDirectory/index.html 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/sample.txt でdummyDirectory/sample.txt 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/hoge.html で404表示できるか
- [x] Chromeで http://localhost:8080/.ignored.html で配信できているか
- [x] Chromeで http://localhost:8080/dummyDirectory/ でdummyDirectory/index.html 表示できるか
- [x] Chromeで http://localhost:8080/largeCapacity.txt で巨大なファイル(1GB)のtxtをダウンロードできるか
- [x] Chromeで http://localhost:8080/sample.mp3 で配信できているか
- [x] Chromeで http://localhost:8080/notExtractFile で配信できているか
- [x] Chromeで http://localhost:8080/unknownExtractFile.hoge で配信できているか
- [x] Chromeで http://localhost:8080/日本語のファイル名.txt で配信できているか
- [x] telnetでGET /index.html HTTP/1.1で200か
- [x] telnetでGET /hoge.html HTTP/1.1で404か
- [x] telnetでGET /index.html HTTP/2で505か
- [x] telnetでPOST /index.html HTTP/1.1で501か
- [x] telnetでhoge hoge hoge hogeで404か

**Comment by sakura818** [comment]
追加チェック

- [x] telnetでPOST /index.html HTTP/2で501か(狙い リクエストとしてのシンタックスはあっているがメソッド名もhttpversionもサポートしていない場合→これは501だと思うなぜならRFC2616の501参照)
- [x] telnetでGET /index.html hogeで400か(狙い リクエストとしてのシンタックスはあっているがhttpversionが存在しない場合)
- [x] telnetでhoge /index.html HTTP/1.1で400か(狙い リクエストとしてのシンタックスはあっているがメソッドが存在しない場合)
- [x] telnetでGET /index.html HTTP/1.1 HTTP/1.1で400か(狙い (空白区切りで4つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)
- [x] telnetでGET /index.htmlで400か(狙い (空白区切りで2つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)
- [x] telnetで/index.htmlで400か(狙い (1つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)

**Comment by sakura818** [comment]
Githubにpushしようとしたら大きすぎる容量のファイルはアップロードできないらしい。
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: File src/main/resources/largeCapacity.txt is 1024.00 MB; this exceeds GitHub's file size limit of 100.00 MB
commitを1GBのファイルを追加する前まで戻り、チェリーピックをすることで解決した

**Comment by sakura818** [comment]
上記のpush問題を解決する際にGitでいろいろなコマンドを入力したため再度ホワイトボックステスト前の最終チェックをする。

- [x] 静的リソースの配信ができ、最新のChromeで閲覧することができる→バージョン 58.0.3029.110 (64-bit)(Chrome最新版であることは確認済)で閲覧することができた
- [x] Firefoxでも少し確認するとなお良い→Firefox53.0.3(64ビット)(Firefox最新版であることは確認済み)で閲覧することができた
- [x] HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること→表示できる
- [x] 200, 404 など各種ステータスコードのサポートがあること→サポートしている
- [x] /sample.mp3 もちゃんと配信されて落ちてきた
- [x] 存在しないファイルに対する拡張子のないリクエストでサーバーが落ちる　localhost:8080/bar にアクセスすると→not found なのでok
- [x] 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる　hoge ファイルを追加したうえで localhost:8080/hoge にアクセスすると
- [x] /foo/ にアクセスしたときに /foo/index.html が配信されずサーバーが落ちる　/ にアクセスしたときの /index.html の配信と一貫性がない→/foo/だとnotfoundになるので修正→
- [x] 名前に日本語を含むファイルが配信できていない　寿司.txt を用意しても localhost:8080/寿司.txt でアクセスできない→notfoundになるので修正→
- [x] 巨大なファイルの配信中に別のクライアントからのリクエストも止まる　2.2GBのファイルを落としながら別のタブでindex.htmlを表示しようとしてもレスポンスが返ってこない。→README.mdにリクエストを同時にさばけない旨を記述する
- [x] ファイル名の先頭に . が付いたHTMLファイルが表示できない　.ignored.html を作成するとファイルのダウンロードが始まり、HTMLが表示されない→html表示できた
- [x] http://localhost:8080/?foo=bar がNotFoundになる　http://localhost:8080/index.html?foo=bar は表示される→URLのクエリの部分を実装していないのでまずRFC2616の3.2などを読んだところ今の課題では必要ないのではと考えた。次の課題でPOSTメソッドが必要になるのでそのときに実装しようと思う。
- [x] Shift-JIS形式で保存したHTMLファイルが文字化けする　常にContent-Typeのencofingがutf-8なのでこうなる　文字コードの指定は仕様に書くようにする→README.mdに文字コードはUTF-8を使用してくださいと記述する
- [x] Content-Typeの確認
- [x] 画像著作権フリーか？→フリー（画像などは自分で作成したもの）
- [x] JavaScriptファイルのContent-Typeはapplication/javascript が推奨
- [x] JPEGファイルのContent-Typeはimage/jpeg
- [x] 複数リクエスト同時にさばける→README.mdにリクエストを同時にさばけない旨を記述する
- [x] 巨大なファイルを配信できるか　http://localhost:8080/largeCapacity.txt
- [x] Chromeで http://localhost:8080/index.html で表示できるか
- [x] Chromeで http://localhost:8080/hoge.html が404表示できるか
- [x] Chromeで http://localhost:8080/ でindex.html 表示できるか
- [x] Chromeで http://localhost:8080 で index.html 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/index.html でdummyDirectory/index.html 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/sample.txt でdummyDirectory/sample.txt 表示できるか
- [x] Chromeで http://localhost:8080/dummyDirectory/hoge.html で404表示できるか
- [x] Chromeで http://localhost:8080/.ignored.html で配信できているか
- [x] Chromeで http://localhost:8080/dummyDirectory/ でdummyDirectory/index.html 表示できるか
- [x] Chromeで http://localhost:8080/largeCapacity.txt で巨大なファイル(1GB)のtxtをダウンロードできるか
- [x] Chromeで http://localhost:8080/sample.mp3 で配信できているか
- [x] Chromeで http://localhost:8080/NotExtractFile で配信できているか
- [x] Chromeで http://localhost:8080/UnknownExtractFile.hoge で配信できているか
- [x] Chromeで http://localhost:8080/日本語のファイル名.txt で配信できているか
- [x] telnetでGET /index.html HTTP/1.1で200か
- [x] telnetでGET /hoge.html HTTP/1.1で404か
- [x] telnetでGET /index.html HTTP/2で505か
- [x] telnetでPOST /index.html HTTP/1.1で501か
- [x] telnetでhoge hoge hoge hogeで404か
- [x] telnetでPOST /index.html HTTP/2で501か(狙い リクエストとしてのシンタックスはあっているがメソッド名もhttpversionもサポートしていない場合→これは501だと思うなぜならRFC2616の501参照)
- [x] telnetでGET /index.html hogeで400か(狙い リクエストとしてのシンタックスはあっているがhttpversionが存在しない場合)
- [x] telnetでhoge /index.html HTTP/1.1で400か(狙い リクエストとしてのシンタックスはあっているがメソッドが存在しない場合)
- [x] telnetでGET /index.html HTTP/1.1 HTTP/1.1で400か(狙い (空白区切りで4つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)
- [x] telnetでGET /index.htmlで400か(狙い (空白区切りで2つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)
- [x] telnetで/index.htmlで400か(狙い (1つの文字列)リクエストとしてのシンタックスはあっていないが中身がぱっと見正しそうな場合)

その他
- POSTおよびqueryは今の課題では必要ないと考えた。次の課題のときに実装する。理由はHTTPのRFCに一般的なサーバが持つメソッドのなかにPOSTが記載されていなかったこと。また、queryに関してはPOSTの実装に付随するものであると考えた。*もしかしたらRFCと違い一般的なサーバという要件のなかにPOSTとqueryがはいっているかもしれない
- ブラウザに返却するべきコンテンツとして File file を使うの自由度が低そうに関しては、次の課題のときに考える。理由は、次の課題でFile fileで困ることの意味がまだあまりわかっていないため。

**Comment by sakura818** [comment]
ホワイトボックステスト前の最終チェックおわり 06/05 13:40
