### ISSUE TITLE
コードレビュー

### ISSUE THREAD

**Issue by lacolaco** [sakura818/write-http-server-01#7]
### `connection()`

- メソッド名は動詞形が望ましいので、 `connection()` よりは `openConnection()` とか `connect()` とかにしましょう
- `serverSocket` がcloseされていない

### `selectStatusCode`

- `File filePath` ではなく `File file` 
- このメソッドを使う側にとってはselectではなく`getStatusCode`のほうがわかりやすい

## HttpRequest.java

- `printHttpRequestLine()` はprintするのが仕事のはずなのに、InputStreamからの読み込み・リクエスト情報のprint、リクエストラインの返却という仕事をしているので、メソッドを分割しましょう `print`するのが仕事であれば戻り値はvoidのはずです 
- 実はInputStreamをフィールドとして保持する意味はあるのかという疑いを持ってみましょう コンストラクタから呼ばれる処理の中でreadしてしまうのであれば、読み取った結果だけをフィールドとして保持すればよさそうです
- `spaceSeparateRequestLine` は`splitRequestLine`がよさそう スペースで区切るかどうかはメソッドの中の問題で、これを呼び出す側は何でsplitされてるかは気にしていないはずです

## HttpResponse.java

- `writeResponseOutputStream`は `writeToOutputStream`のほうがはっきりわかる気がする

## HttpResponseStatusLineContent.java

- コンストラクタでstatusCodeを受け取っておくほうが自然。このクラスが使うステータスコードは後から変わらないし必ず必要になるから
- `createHttpResponseStatusLine`という名前は、このクラスの名前の時点でHttpResponseのStatusLineを扱うことはわかっているので、冗長すぎる `create()`でも通じる
- あるいは、`Builder`という単語を使ってみるとわかりやすいかも。`HttpResponseStatusLineBuilder`クラスと、`String build()`メソッドという関係がこの場合ふさわしいように思う
- `createReasonPhrase` は `getReasonPhrase` のほうが自然

## HttpResponseMessageHeaderContent.java

HttpResponseStatusLineContentとだいたい同じ指摘

- `File filePath` ではなく `File file`
- 最終的に必要なのは拡張子を手に入れるためのファイル名だけなので、`File`を受け取る必要はなくて、このクラスのコンストラクタでファイル名だけを受け取っておけばいいんじゃなかろうか

## HttpResponseMessageBodyContent.java

これもまた同様。

- このクラスの挙動はFileとステータスコードによって決まるので、その2つをコンストラクタで受け取っておくとよいのではなかろうか

この3つの `HttpResponse*Content`クラスをそれぞれBuilder/build()の関係にできれば、HttpResponseクラスは次のようなスッキリしたコードになる

```
        /** HttpResponseのStatusLineをバイト出力ストリームに書き込む */
        HttpResponseStatusLineBuilder statusLineBuilder = new HttpResponseStatusLineBuilder(statusCode);
        printWriter.println(statusLineBuilder.build());

        /** HttpResponseのMessageHeaderをバイト出力ストリームに書き込む */
        HttpResponseMessageHeaderBuilder messageHeaderBuilder = new HttpResponseMessageHeaderBuilder(file.getName());
        printWriter.println(messageHeaderBuilder.build());

        /** HttpResponseのMessageBodyをバイト出力ストリームに書き込む */
        HttpResponseMessageBodyBuilder messageBodyBuilder = new HttpResponseMessageBodyBuilder(file, statusCode);
        outputStream.write(messageBodyBuilder.build());
```

同じような仕事をするクラスは、同じような使い方ができたほうがコードを読むときの理解が簡単になります

**Comment by sakura818** [comment]
HttpServer.java
* [x] connect()に変更
* [x] serverSocket をclose
* [x] File filePath ではなく File file
* [x] getStatusCode

HttpRequest.java
* [x] printHttpRequestLine()
* [x] InputStreamをフィールドとして保持する意味
* [x] spaceSeparateRequestLine はsplitRequestLine

HttpResponse.java
* [x] writeResponseOutputStreamは writeToOutputStream

HttpResponseStatusLineContent.java
* [x] コンストラクタでstatusCodeを受け取っておく
* [x] Builderという単語を使ってみるとわかりやすいかも。HttpResponseStatusLineBuilderクラスと、String build()メソッド
* [x] createReasonPhrase は getReasonPhrase

HttpResponseMessageHeaderContent.java
* [x] File filePath ではなく File file
* [x] Builderという単語を使ってみるとわかりやすいかも。HttpResponseMessageHeaderBuilderクラスと、String build()メソッド
* [x] コンストラクタでファイル名だけを受け取っておけばいい

HttpResponseMessageBodyContent.java
* [x] File filePath ではなく File file
* [x] Fileとステータスコードによって決まるので、その2つをコンストラクタで受け取っておく
* [x] Builderという単語を使ってみるとわかりやすいかも。HttpResponseMessageBodyBuilderクラスと、String build()メソッド
* [x] HttpResponse*ContentクラスをそれぞれBuilder/build()の関係にする

**Comment by lacolaco** [comment]
## HttpRequest.java

- `printRequestLine` が、与えられた文字列をprintlnに渡すだけになってて、これはメソッドに分ける意味ない気がする
- `String file;` は `filePath` にすべき `file` と `filePath` を区別しましょう
- `splitRequestLine` がsplitして3つに分割するメソッドだったはずなのに、requestUriだけを返すようになってる。メソッドの名前と責務が一致してない

## HttpResponseMessageHeaderBuilderTest.java

- クラスフィールドの`file`は初期化されていないまま、`HttpResponseMessageHeaderBuilder`のコンストラクタに渡されているけど、これは微妙そう

## HttpResponseStatusLineBuilderTest.java

- こちらも。statusCodeは初期化されていないままコンストラクタ引数になっていて、よくわからないテストになっている

## HttpResponseMessageBodyBuilderTest.java

- この中でHttpResponseMessageBodyBuilderのテストしてなくない？

----

だんだんJavaっぽいコードになってよくなってきた

**Comment by sakura818** [comment]
* [x] printRequestLine が、与えられた文字列をprintlnに渡すだけになってて、これはメソッドに分ける意味ない気がする
* [x]  file と filePath を区別
* [x] splitRequestLine メソッドの名前と責務が一致してない
* [x] クラスフィールドのfileは初期化されていないまま、HttpResponseMessageHeaderBuilderのコンストラクタに渡されている
* [x] statusCodeは初期化されていないままコンストラクタ引数
* [x] HttpResponseMessageBodyBuilderのテスト

**Comment by lacolaco** [comment]
## HttpRequestTest.java

- テストのメソッド名

`requestLineからstatusCode200を判断するテスト` ではなく、 `GETリクエストにはステータスコード200を返す` というほうがいい。「◯◯なとき〜〜になる」というのがテストの説明として適切
同様に同じようなテストのメソッド名をつけなおしてみよう。 `requestLineからstatusCode501を判断するテスト`ではなく `POSTリクエストにはステータスコード501を返す` とすれば、テストの中身を読まずともCIがgreenということだけでこのサーバーがPOSTを弾けることがわかる

`requestLineから相対パスのrequestUriを抜き出すテスト`はそのままで適切だと思う

## HttpResponseMessageBodyBuilderTest.java

前にも言った気がするけど、このテストはHttpResponseMessageBodyBuilderをテストするためのものなのに、HttpResponseMessageBodyBuilderは一度も使われてないですね。テスト用に用意したHTMLを読み出しているだけで、アプリケーションコードは何もテストされてない
HttpResponseMessageBodyBuilderにfileを渡して、build()で返ってくるbyte[]をテストしないと意味ないですね

## HttpResponseMessageHeaderBuilderTest.java

これも同じです。`buildメソッドのテスト`ではHttpResponseMessageHeaderBuilderでやってることと同じようなことをテストコードに書いてるけど、それはHttpResponseMessageHeaderBuilderをテストしていることにはなりません

```
HttpResponseMessageHeaderBuilder httpResponseMessageHeaderBuilder = new HttpResponseMessageHeaderBuilder(file);
```

変数名長いので `HttpResponseMessageHeaderBuilder builder = new HttpResponseMessageHeaderBuilder(file);` とかでよいですよ。型名は見れば分かるし変数のスコープも狭いので短い名前でも十分にわかります

## HttpResponseStatusLineBuilderTest.java

これも同じくbuildメソッドのテストができていません

## HttpResponseTest.java

これも同じ。`createHttpResponseContent`が使われてない

## HttpServerTest.java

これも同じく、`connectメソッドのテスト` がconnectメソッドをテストしていない

**Comment by sakura818** [comment]
- [x] テストコードのメソッド名の変更
- [x]  使われていない→使う

**Comment by lacolaco** [comment]
## HttpServer.java

この部分

```java
                    switch (statusCode) {
                        case OK:
                            file = new File(this.FILEPATH_DIR, httpRequest.getUriPath());
                            statusCode = catchStatusCode(file);
                            if (statusCode == OK) {
                                file = new File(this.FILEPATH_DIR, httpRequest.getUriPath());
                            } else if (statusCode == NOT_FOUND) {
                                file = new File(this.FILEPATH_DIR, "NotFound.html");
                            }
                            break;
                        case BAD_REQUEST:
                            file = new File(this.FILEPATH_DIR, "BadRequest.html");
                            break;
                        case NOT_IMPLEMENTED:
                            file = new File(this.FILEPATH_DIR, "NotImplemented.html");
                            break;
                        case HTTP_VERSION_NOT_SUPPORTED:
                            file = new File(this.FILEPATH_DIR, "HttpVersionNotSupported.html");
                            break;
                    }
```

statusCodeでswitchしつつcaseの中でまたstatusCodeを書き換えてif文でチェックする、というのはイケてない気がする。僕なら次のように書くかな

```java
                    if (statusCode == OK) {
                        file = new File(this.FILEPATH_DIR, httpRequest.getUriPath());
                        if (!file.exists()) {
                            statusCode = NOT_FOUND;
                        }
                    }
                    if (statusCode != OK) {
                        switch (statusCode) {
                            case NOT_FOUND:
                                file = new File(this.FILEPATH_DIR, "NotFound.html");
                                break;
                            case BAD_REQUEST:
                                file = new File(this.FILEPATH_DIR, "BadRequest.html");
                                break;
                            case NOT_IMPLEMENTED:
                                file = new File(this.FILEPATH_DIR, "NotImplemented.html");
                                break;
                            case HTTP_VERSION_NOT_SUPPORTED:
                                file = new File(this.FILEPATH_DIR, "HttpVersionNotSupported.html");
                                break;
                        }
                    }
```

switch文は異常系のときしか通らなくなって比較的読みやすくなる

## HttpRequest.java

HTTPメソッドとかバージョンについて、availableなリストを作るのは正しいと思うんだけど、unavailableなリストも持つ意味はなんだろう。普通はavailableなリストの中に見つからないものはすべてunavailableだという判定でいいと思う

**Comment by sakura818** [comment]
- [x] switch
- [x] リストのrename

**Comment by sakura818** [comment]
- [x] catchStatucCodeもう必要ないから削除
